### ISSUE TITLE
Invalid custom URLs when copying from Facebook

### ISSUE THREAD

**Issue by evilpegasus** [evilpegasus/Yearbook#4]
Facebook adds their own trackers to the end of URLs sent. 'Go to Someone Else's Yearbook' will fail if these links are pasted in.

https://yearbook-hhs.web.app/app.html?user=[abc]&fbclid=[xyz]

**Comment by arnavthareja** [comment]
this issue stems from facebook redirecting links through their own domain, so copying the link address will give a link that does not start with https://yearbook-hhs.web.app, so it will not be recognized as a valid link. The fix for this bug is coming soon.

**Comment by arnavthareja** [comment]
We have decided to not fix this, as the facebook redirect links do not start with https://yearbook-hhs.web.app, and we only want to redirect to links that are inside our domain.

For using 'Go to Someone Else's Yearbook' in the future for links sent through facebook and other social media, you should copy the URL as text instead of copying the link address.
